"""Write a minimal CGNS/HDF5 file, so that the CGNS reader can be measured at all.

**Why this exists.** The toolkit ships three CGNS reader classes and **no writer** (measured 2026-08-24
against VTK 9.5.2), so XC-085's rule - fixtures are generated by this product's own test code wherever
the format allows it - has no writer to use. Its stated fallback is an outside file with recorded terms,
which nobody has supplied. A format that cannot be exercised is a format whose support level is a claim.

So this writes the CGNS/HDF5 node layout directly with h5py. CGNS/HDF5 stores every node as an HDF5
group carrying `name`, `label`, `type` and `flags` attributes and an optional ` data` dataset; the
layout is documented by the CGNS standard (E-137).

**What this is not.** It is not a CGNS writer and must not become one. It writes exactly enough for the
reader to have something to read - one base, one zone, coordinates, one element section, one flow
solution and one `DimensionalUnits` declaration - so that questions about the reader can be answered by
measurement instead of assumption. A file it produces proves what the reader does with *this* file; a
real solver's CGNS is wider, and the support level says so.

Run in a prepared spike environment (`pip install vtk==9.5.2 numpy h5py`).
"""

from __future__ import annotations

import sys
from pathlib import Path



sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tests"))
from cgns_fixture import write_minimal_cgns  # noqa: E402


def main() -> int:
    target = Path(__file__).with_name("artifacts") / "minimal.cgns"
    target.parent.mkdir(exist_ok=True)
    write_minimal_cgns(target)
    print(f"wrote {target} ({target.stat().st_size} bytes)")

    from vtkmodules.vtkIOCGNSReader import vtkCGNSReader

    reader = vtkCGNSReader()
    reader.SetFileName(str(target))
    reader.UpdateInformation()
    points_selection = reader.GetPointDataArraySelection()
    cells_selection = reader.GetCellDataArraySelection()
    print("point arrays offered:", [points_selection.GetArrayName(i)
                                    for i in range(points_selection.GetNumberOfArrays())])
    print("            statuses:", [points_selection.GetArraySetting(i)
                                    for i in range(points_selection.GetNumberOfArrays())])
    print("cell arrays offered :", [cells_selection.GetArrayName(i)
                                    for i in range(cells_selection.GetNumberOfArrays())])
    reader.Update()
    output = reader.GetOutput()
    print("output:", output.GetClassName(), output.GetNumberOfBlocks(), "blocks")

    def walk(nodeobj, depth=0):
        from vtkmodules.vtkCommonDataModel import vtkCompositeDataSet, vtkMultiBlockDataSet
        for index in range(nodeobj.GetNumberOfBlocks()):
            meta = nodeobj.GetMetaData(index)
            name = meta.Get(vtkMultiBlockDataSet.NAME()) if meta and meta.Has(vtkMultiBlockDataSet.NAME()) else f"[{index}]"
            child = nodeobj.GetBlock(index)
            if child is None:
                print("  " * depth, name, "-> None")
            elif isinstance(child, vtkCompositeDataSet):
                print("  " * depth, name, "->", child.GetClassName())
                walk(child, depth + 1)
            else:
                data = child.GetPointData()
                print("  " * depth, name, "->", child.GetClassName(),
                      child.GetNumberOfPoints(), "pts", child.GetNumberOfCells(), "cells",
                      [data.GetArrayName(i) for i in range(data.GetNumberOfArrays())])

    walk(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
