"""The colour maps this build ships, with where each came from and under what terms.

A colour map is part of how a number is read (XC-111): a contour is a value seen through colour, and
a map that is not perceptually uniform puts steps in the picture that are not in the data. The
default is therefore a viridis-class map, and every map here says whether it is uniform.

**Source and licence.** `viridis` and `plasma` are the 256-entry tables published by their authors -
Nathaniel J. Smith, Stéfan van der Walt and (for viridis) Eric Firing - in the BIDS `colormap`
repository, whose header releases the file "under the CC0 license / public domain dedication" (E-193).
They are reproduced here byte for byte as sRGB hex triplets, rounded from the published floats.
`greys` is generated: a straight line in sRGB between the two stops the interface's own token
`--map-greys` uses, so the picture and the chrome agree on what grey means.

Generated by archive/_gen_colour_maps.py from the authors' file; edit the generator, not this.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ColourMap:
    """One map: its identity, whether it is perceptually uniform, and where it came from."""

    id: str
    name: str
    uniform: bool
    source: str
    licence: str
    samples: tuple[str, ...]

    def rgb(self) -> tuple[tuple[float, float, float], ...]:
        """The samples as floats in 0..1, in order from the low end of the range to the high."""
        return tuple(
            (int(one[1:3], 16) / 255.0, int(one[3:5], 16) / 255.0, int(one[5:7], 16) / 255.0)
            for one in self.samples
        )


VIRIDIS = ColourMap(
    id="viridis",
    name="Viridis",
    uniform=True,
    source="BIDS/colormap colormaps.py (Smith, van der Walt, Firing)",
    licence="CC0 1.0 / public domain dedication",
    samples=(
    "#440154", "#440256", "#450457", "#450559", "#46075a", "#46085c", "#460a5d", "#460b5e",
    "#470d60", "#470e61", "#471063", "#471164", "#471365", "#481467", "#481668", "#481769",
    "#48186a", "#481a6c", "#481b6d", "#481c6e", "#481d6f", "#481f70", "#482071", "#482173",
    "#482374", "#482475", "#482576", "#482677", "#482878", "#482979", "#472a7a", "#472c7a",
    "#472d7b", "#472e7c", "#472f7d", "#46307e", "#46327e", "#46337f", "#463480", "#453581",
    "#453781", "#453882", "#443983", "#443a83", "#443b84", "#433d84", "#433e85", "#423f85",
    "#424086", "#424186", "#414287", "#414487", "#404588", "#404688", "#3f4788", "#3f4889",
    "#3e4989", "#3e4a89", "#3e4c8a", "#3d4d8a", "#3d4e8a", "#3c4f8a", "#3c508b", "#3b518b",
    "#3b528b", "#3a538b", "#3a548c", "#39558c", "#39568c", "#38588c", "#38598c", "#375a8c",
    "#375b8d", "#365c8d", "#365d8d", "#355e8d", "#355f8d", "#34608d", "#34618d", "#33628d",
    "#33638d", "#32648e", "#32658e", "#31668e", "#31678e", "#31688e", "#30698e", "#306a8e",
    "#2f6b8e", "#2f6c8e", "#2e6d8e", "#2e6e8e", "#2e6f8e", "#2d708e", "#2d718e", "#2c718e",
    "#2c728e", "#2c738e", "#2b748e", "#2b758e", "#2a768e", "#2a778e", "#2a788e", "#29798e",
    "#297a8e", "#297b8e", "#287c8e", "#287d8e", "#277e8e", "#277f8e", "#27808e", "#26818e",
    "#26828e", "#26828e", "#25838e", "#25848e", "#25858e", "#24868e", "#24878e", "#23888e",
    "#23898e", "#238a8d", "#228b8d", "#228c8d", "#228d8d", "#218e8d", "#218f8d", "#21908d",
    "#21918c", "#20928c", "#20928c", "#20938c", "#1f948c", "#1f958b", "#1f968b", "#1f978b",
    "#1f988b", "#1f998a", "#1f9a8a", "#1e9b8a", "#1e9c89", "#1e9d89", "#1f9e89", "#1f9f88",
    "#1fa088", "#1fa188", "#1fa187", "#1fa287", "#20a386", "#20a486", "#21a585", "#21a685",
    "#22a785", "#22a884", "#23a983", "#24aa83", "#25ab82", "#25ac82", "#26ad81", "#27ad81",
    "#28ae80", "#29af7f", "#2ab07f", "#2cb17e", "#2db27d", "#2eb37c", "#2fb47c", "#31b57b",
    "#32b67a", "#34b679", "#35b779", "#37b878", "#38b977", "#3aba76", "#3bbb75", "#3dbc74",
    "#3fbc73", "#40bd72", "#42be71", "#44bf70", "#46c06f", "#48c16e", "#4ac16d", "#4cc26c",
    "#4ec36b", "#50c46a", "#52c569", "#54c568", "#56c667", "#58c765", "#5ac864", "#5cc863",
    "#5ec962", "#60ca60", "#63cb5f", "#65cb5e", "#67cc5c", "#69cd5b", "#6ccd5a", "#6ece58",
    "#70cf57", "#73d056", "#75d054", "#77d153", "#7ad151", "#7cd250", "#7fd34e", "#81d34d",
    "#84d44b", "#86d549", "#89d548", "#8bd646", "#8ed645", "#90d743", "#93d741", "#95d840",
    "#98d83e", "#9bd93c", "#9dd93b", "#a0da39", "#a2da37", "#a5db36", "#a8db34", "#aadc32",
    "#addc30", "#b0dd2f", "#b2dd2d", "#b5de2b", "#b8de29", "#bade28", "#bddf26", "#c0df25",
    "#c2df23", "#c5e021", "#c8e020", "#cae11f", "#cde11d", "#d0e11c", "#d2e21b", "#d5e21a",
    "#d8e219", "#dae319", "#dde318", "#dfe318", "#e2e418", "#e5e419", "#e7e419", "#eae51a",
    "#ece51b", "#efe51c", "#f1e51d", "#f4e61e", "#f6e620", "#f8e621", "#fbe723", "#fde725",
    ),
)

PLASMA = ColourMap(
    id="plasma",
    name="Plasma",
    uniform=True,
    source="BIDS/colormap colormaps.py (Smith, van der Walt)",
    licence="CC0 1.0 / public domain dedication",
    samples=(
    "#0d0887", "#100788", "#130789", "#16078a", "#19068c", "#1b068d", "#1d068e", "#20068f",
    "#220690", "#240691", "#260591", "#280592", "#2a0593", "#2c0594", "#2e0595", "#2f0596",
    "#310597", "#330597", "#350498", "#370499", "#38049a", "#3a049a", "#3c049b", "#3e049c",
    "#3f049c", "#41049d", "#43039e", "#44039e", "#46039f", "#48039f", "#4903a0", "#4b03a1",
    "#4c02a1", "#4e02a2", "#5002a2", "#5102a3", "#5302a3", "#5502a4", "#5601a4", "#5801a4",
    "#5901a5", "#5b01a5", "#5c01a6", "#5e01a6", "#6001a6", "#6100a7", "#6300a7", "#6400a7",
    "#6600a7", "#6700a8", "#6900a8", "#6a00a8", "#6c00a8", "#6e00a8", "#6f00a8", "#7100a8",
    "#7201a8", "#7401a8", "#7501a8", "#7701a8", "#7801a8", "#7a02a8", "#7b02a8", "#7d03a8",
    "#7e03a8", "#8004a8", "#8104a7", "#8305a7", "#8405a7", "#8606a6", "#8707a6", "#8808a6",
    "#8a09a5", "#8b0aa5", "#8d0ba5", "#8e0ca4", "#8f0da4", "#910ea3", "#920fa3", "#9410a2",
    "#9511a1", "#9613a1", "#9814a0", "#99159f", "#9a169f", "#9c179e", "#9d189d", "#9e199d",
    "#a01a9c", "#a11b9b", "#a21d9a", "#a31e9a", "#a51f99", "#a62098", "#a72197", "#a82296",
    "#aa2395", "#ab2494", "#ac2694", "#ad2793", "#ae2892", "#b02991", "#b12a90", "#b22b8f",
    "#b32c8e", "#b42e8d", "#b52f8c", "#b6308b", "#b7318a", "#b83289", "#ba3388", "#bb3488",
    "#bc3587", "#bd3786", "#be3885", "#bf3984", "#c03a83", "#c13b82", "#c23c81", "#c33d80",
    "#c43e7f", "#c5407e", "#c6417d", "#c7427c", "#c8437b", "#c9447a", "#ca457a", "#cb4679",
    "#cc4778", "#cc4977", "#cd4a76", "#ce4b75", "#cf4c74", "#d04d73", "#d14e72", "#d24f71",
    "#d35171", "#d45270", "#d5536f", "#d5546e", "#d6556d", "#d7566c", "#d8576b", "#d9586a",
    "#da5a6a", "#da5b69", "#db5c68", "#dc5d67", "#dd5e66", "#de5f65", "#de6164", "#df6263",
    "#e06363", "#e16462", "#e26561", "#e26660", "#e3685f", "#e4695e", "#e56a5d", "#e56b5d",
    "#e66c5c", "#e76e5b", "#e76f5a", "#e87059", "#e97158", "#e97257", "#ea7457", "#eb7556",
    "#eb7655", "#ec7754", "#ed7953", "#ed7a52", "#ee7b51", "#ef7c51", "#ef7e50", "#f07f4f",
    "#f0804e", "#f1814d", "#f1834c", "#f2844b", "#f3854b", "#f3874a", "#f48849", "#f48948",
    "#f58b47", "#f58c46", "#f68d45", "#f68f44", "#f79044", "#f79143", "#f79342", "#f89441",
    "#f89540", "#f9973f", "#f9983e", "#f99a3e", "#fa9b3d", "#fa9c3c", "#fa9e3b", "#fb9f3a",
    "#fba139", "#fba238", "#fca338", "#fca537", "#fca636", "#fca835", "#fca934", "#fdab33",
    "#fdac33", "#fdae32", "#fdaf31", "#fdb130", "#fdb22f", "#fdb42f", "#fdb52e", "#feb72d",
    "#feb82c", "#feba2c", "#febb2b", "#febd2a", "#febe2a", "#fec029", "#fdc229", "#fdc328",
    "#fdc527", "#fdc627", "#fdc827", "#fdca26", "#fdcb26", "#fccd25", "#fcce25", "#fcd025",
    "#fcd225", "#fbd324", "#fbd524", "#fbd724", "#fad824", "#fada24", "#f9dc24", "#f9dd25",
    "#f8df25", "#f8e125", "#f7e225", "#f7e425", "#f6e626", "#f6e826", "#f5e926", "#f5eb27",
    "#f4ed27", "#f3ee27", "#f3f027", "#f2f227", "#f1f426", "#f1f525", "#f0f724", "#f0f921",
    ),
)

GREYS = ColourMap(
    id="greys",
    name="グレー",
    uniform=True,
    source="generated: a straight sRGB line from #111111 to #f5f5f5",
    licence="this project",
    samples=(
    "#111111", "#121212", "#131313", "#141414", "#151515", "#151515", "#161616", "#171717",
    "#181818", "#191919", "#1a1a1a", "#1b1b1b", "#1c1c1c", "#1d1d1d", "#1e1e1e", "#1e1e1e",
    "#1f1f1f", "#202020", "#212121", "#222222", "#232323", "#242424", "#252525", "#262626",
    "#262626", "#272727", "#282828", "#292929", "#2a2a2a", "#2b2b2b", "#2c2c2c", "#2d2d2d",
    "#2e2e2e", "#2f2f2f", "#2f2f2f", "#303030", "#313131", "#323232", "#333333", "#343434",
    "#353535", "#363636", "#373737", "#373737", "#383838", "#393939", "#3a3a3a", "#3b3b3b",
    "#3c3c3c", "#3d3d3d", "#3e3e3e", "#3f3f3f", "#3f3f3f", "#404040", "#414141", "#424242",
    "#434343", "#444444", "#454545", "#464646", "#474747", "#484848", "#484848", "#494949",
    "#4a4a4a", "#4b4b4b", "#4c4c4c", "#4d4d4d", "#4e4e4e", "#4f4f4f", "#505050", "#505050",
    "#515151", "#525252", "#535353", "#545454", "#555555", "#565656", "#575757", "#585858",
    "#595959", "#595959", "#5a5a5a", "#5b5b5b", "#5c5c5c", "#5d5d5d", "#5e5e5e", "#5f5f5f",
    "#606060", "#616161", "#616161", "#626262", "#636363", "#646464", "#656565", "#666666",
    "#676767", "#686868", "#696969", "#6a6a6a", "#6a6a6a", "#6b6b6b", "#6c6c6c", "#6d6d6d",
    "#6e6e6e", "#6f6f6f", "#707070", "#717171", "#727272", "#727272", "#737373", "#747474",
    "#757575", "#767676", "#777777", "#787878", "#797979", "#7a7a7a", "#7b7b7b", "#7b7b7b",
    "#7c7c7c", "#7d7d7d", "#7e7e7e", "#7f7f7f", "#808080", "#818181", "#828282", "#838383",
    "#838383", "#848484", "#858585", "#868686", "#878787", "#888888", "#898989", "#8a8a8a",
    "#8b8b8b", "#8b8b8b", "#8c8c8c", "#8d8d8d", "#8e8e8e", "#8f8f8f", "#909090", "#919191",
    "#929292", "#939393", "#949494", "#949494", "#959595", "#969696", "#979797", "#989898",
    "#999999", "#9a9a9a", "#9b9b9b", "#9c9c9c", "#9c9c9c", "#9d9d9d", "#9e9e9e", "#9f9f9f",
    "#a0a0a0", "#a1a1a1", "#a2a2a2", "#a3a3a3", "#a4a4a4", "#a5a5a5", "#a5a5a5", "#a6a6a6",
    "#a7a7a7", "#a8a8a8", "#a9a9a9", "#aaaaaa", "#ababab", "#acacac", "#adadad", "#adadad",
    "#aeaeae", "#afafaf", "#b0b0b0", "#b1b1b1", "#b2b2b2", "#b3b3b3", "#b4b4b4", "#b5b5b5",
    "#b6b6b6", "#b6b6b6", "#b7b7b7", "#b8b8b8", "#b9b9b9", "#bababa", "#bbbbbb", "#bcbcbc",
    "#bdbdbd", "#bebebe", "#bebebe", "#bfbfbf", "#c0c0c0", "#c1c1c1", "#c2c2c2", "#c3c3c3",
    "#c4c4c4", "#c5c5c5", "#c6c6c6", "#c7c7c7", "#c7c7c7", "#c8c8c8", "#c9c9c9", "#cacaca",
    "#cbcbcb", "#cccccc", "#cdcdcd", "#cecece", "#cfcfcf", "#cfcfcf", "#d0d0d0", "#d1d1d1",
    "#d2d2d2", "#d3d3d3", "#d4d4d4", "#d5d5d5", "#d6d6d6", "#d7d7d7", "#d7d7d7", "#d8d8d8",
    "#d9d9d9", "#dadada", "#dbdbdb", "#dcdcdc", "#dddddd", "#dedede", "#dfdfdf", "#e0e0e0",
    "#e0e0e0", "#e1e1e1", "#e2e2e2", "#e3e3e3", "#e4e4e4", "#e5e5e5", "#e6e6e6", "#e7e7e7",
    "#e8e8e8", "#e8e8e8", "#e9e9e9", "#eaeaea", "#ebebeb", "#ececec", "#ededed", "#eeeeee",
    "#efefef", "#f0f0f0", "#f1f1f1", "#f1f1f1", "#f2f2f2", "#f3f3f3", "#f4f4f4", "#f5f5f5",
    ),
)

#: Every map this build knows, by the identifier a view definition names (CT-004 `colouring.colourMap`).
COLOUR_MAPS: dict[str, ColourMap] = {one.id: one for one in (VIRIDIS, PLASMA, GREYS)}

#: The map a view gets when it names none (XC-111).
DEFAULT_COLOUR_MAP = VIRIDIS.id
