"""Writing a minimal CGNS file, because the toolkit ships no CGNS writer.

XC-085 says fixtures are generated by this project's own test code wherever the format allows it, and
records CGNS as the one exception - "CGNS has no writer, so its fixture comes from an outside file whose
source and terms are recorded". Measured 2026-08-24: the toolkit ships three CGNS **reader** classes and
no writer, so that much is right (E-137). The exception is not: CGNS/HDF5 stores every node as an HDF5
group with `name`, `label`, `type` and `flags` attributes and an optional ` data` dataset, and h5py
writes that directly. So the rule holds for six of six Verified formats.

**This is not a CGNS writer and must not become one.** It writes exactly enough for the reader to have
something to read - one base, one unstructured zone, coordinates, one element section, one flow solution
and one `DimensionalUnits` declaration. What a test built on it proves is bounded, and the format's
stated gaps say so.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

# Imported plainly: `conftest.requires_h5py()` decides whether a caller may run at all, so a second
# opinion about it here would be a second place to keep in step.
import h5py

# CGNS/HDF5 marks every node with these four attributes. Fixed-length byte strings, as the standard
# specifies - h5py's variable-length default produces a file the reader rejects without saying why.
_NAME = h5py.string_dtype("ascii", 33)
_LABEL = h5py.string_dtype("ascii", 33)
_TYPE = h5py.string_dtype("ascii", 3)


def text(value: str, width: int | None = None) -> np.ndarray:
    """A CGNS `C1` payload: native chars, not an HDF5 string type.

    h5py's string dtypes produce a file the reader opens and then misreads - `ZoneType` came back
    unread and the zone was taken for a structured one, with 8 points where the file has 4. The
    standard says C1 is `H5T_NATIVE_CHAR`, which is int8 here.
    """
    padded = value.ljust(width) if width else value
    return np.frombuffer(padded.encode("ascii"), dtype=np.int8)


def node(parent: h5py.Group, name: str, label: str, data=None, dtype: str = "MT") -> h5py.Group:
    """One CGNS node: a group with its four attributes and, where it has one, its ` data` dataset."""
    group = parent.create_group(name)
    group.attrs.create("name", name.encode("ascii"), dtype=_NAME)
    group.attrs.create("label", label.encode("ascii"), dtype=_LABEL)
    group.attrs.create("type", dtype.encode("ascii"), dtype=_TYPE)
    group.attrs.create("flags", np.array([1], dtype=np.int32))
    if data is not None:
        group.create_dataset(" data", data=data)
    return group


def write_minimal_cgns(path: Path) -> Path:
    """A single-zone unstructured CGNS file: 4 points, 2 triangles, one field, units declared."""
    points = np.array(
        [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [1.0, 1.0, 0.0]], dtype=np.float64
    )
    # CGNS element connectivity is 1-based.
    connectivity = np.array([1, 2, 3, 2, 4, 3], dtype=np.int32)
    field = np.array([10.0, 20.0, 90.0, 40.0], dtype=np.float64)

    with h5py.File(path, "w") as handle:
        handle.attrs.create("name", b"HDF5 MotherNode", dtype=_NAME)
        handle.attrs.create("label", b"Root Node of HDF5 File", dtype=_LABEL)
        handle.attrs.create("type", b"MT", dtype=_TYPE)
        handle.attrs.create("flags", np.array([1], dtype=np.int32))
        node(handle, "CGNSLibraryVersion", "CGNSLibraryVersion_t",
             np.array([4.2], dtype=np.float32), "R4")

        base = node(handle, "Base", "CGNSBase_t", np.array([2, 3], dtype=np.int32), "I4")

        # The declaration this product cares about and the toolkit's reader has no method for (E-130).
        # Metre, kilogram, second, kelvin, radian - the CGNS enumerations, in the standard's order.
        node(base, "DataClass", "DataClass_t", text("Dimensional"), "C1")
        node(base, "DimensionalUnits", "DimensionalUnits_t",
             np.concatenate([text(u, 32) for u in
                             ("Meter", "Kilogram", "Second", "Kelvin", "Radian")]), "C1")

        zone = node(base, "Zone", "Zone_t",
                    np.array([[len(points), 2, 0]], dtype=np.int32), "I4")
        node(zone, "ZoneType", "ZoneType_t", text("Unstructured"), "C1")

        grid = node(zone, "GridCoordinates", "GridCoordinates_t")
        for axis, column in zip("XYZ", points.T):
            node(grid, f"Coordinate{axis}", "DataArray_t", column, "R8")

        # TRI_3 is element type 5 in the CGNS element enumeration.
        section = node(zone, "Elements", "Elements_t", np.array([5, 0], dtype=np.int32), "I4")
        node(section, "ElementRange", "IndexRange_t", np.array([1, 2], dtype=np.int32), "I4")
        node(section, "ElementConnectivity", "DataArray_t", connectivity, "I4")

        solution = node(zone, "FlowSolution", "FlowSolution_t")
        node(solution, "GridLocation", "GridLocation_t", text("Vertex"), "C1")
        node(solution, "stress", "DataArray_t", field, "R8")

    return path


def write_transient_cgns(path: Path, values: tuple[float, ...] = (0.0, 0.5)) -> Path:
    """The same file with a declared sequence: `BaseIterativeData_t` holding `TimeValues`.

    This is the case that matters for GL-036 - the file states the values and states nothing about what
    they are, and both halves have to survive to the @Case.
    """
    write_minimal_cgns(path)
    with h5py.File(path, "a") as handle:
        base = handle["Base"]
        iterative = node(base, "BaseIterativeData", "BaseIterativeData_t",
                         np.array([len(values)], np.int32), "I4")
        node(iterative, "TimeValues", "DataArray_t", np.array(values, np.float64), "R8")

        zone = base["Zone"]
        names = b""
        for index in range(len(values)):
            name = "FlowSolution" if index == 0 else f"FlowSolution{index + 1}"
            names += name.encode("ascii").ljust(32)
            if index:
                solution = node(zone, name, "FlowSolution_t")
                node(solution, "GridLocation", "GridLocation_t", text("Vertex"), "C1")
                node(solution, "stress", "DataArray_t",
                     np.array([10.0, 20.0, 90.0, 40.0]) + index, "R8")
        pointers = node(zone, "ZoneIterativeData", "ZoneIterativeData_t")
        node(pointers, "FlowSolutionPointers", "DataArray_t",
             np.frombuffer(names, dtype=np.int8).reshape(len(values), 32), "C1")
    return path
