"""CGNS: the one format that declares its units, and the one this product cannot read them from.

The fixture is written here rather than collected. The toolkit ships three CGNS reader classes and **no
writer** (E-137), so XC-085's rule - fixtures are generated by this project's own test code wherever the
format allows it - has no writer to reach for. Its stated fallback was an outside file with recorded
terms; writing the CGNS/HDF5 node layout directly turns out to be the shorter route, and it keeps the
rule intact for six of six Verified formats rather than five.

What that fixture proves is bounded and the support level says so: one base, one unstructured zone, one
field, units declared. Multi-zone, structured zones, boundary conditions and ADF-format CGNS are
unexercised.

Verifies: ingest/AC-032, AC-033, AC-034, ingest/TASK-032.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from conftest import requires_h5py, requires_vtk

requires_vtk()
requires_h5py()

import numpy as np  # noqa: E402

from domain_core.reported_value import Caveat  # noqa: E402
from engine import reader  # noqa: E402
from cgns_fixture import write_minimal_cgns  # noqa: E402


@pytest.fixture
def minimal(tmp_path: Path) -> Path:
    return write_minimal_cgns(tmp_path / "minimal.cgns")


class TestWhatTheFileHoldsArrives:
    def test_the_zone_reads_as_one_part_of_one_case(self, minimal: Path) -> None:
        case = reader.read_case(minimal)

        assert case.contents.parts == 1
        assert case.present[0].label.endswith("Base / Zone")

    def test_the_geometry_is_the_geometry_the_file_declares(self, minimal: Path) -> None:
        dataset = reader.read_case(minimal).present[0].dataset

        assert dataset.point_count == 4
        assert dataset.cell_count == 2
        assert set(dataset.cells.types.tolist()) == {5}  # VTK_TRIANGLE

    def test_the_result_arrives(self, minimal: Path) -> None:
        """The reader reads no arrays until each is switched on (E-137) - the same defect as Exodus
        through a different API, which is why the check that catches it is shared."""
        dataset = reader.read_case(minimal).present[0].dataset

        assert sorted(dataset.fields) == ["stress"]
        assert dataset.maximum("stress").value == 90.0

    def test_the_defaults_would_have_dropped_it(self, minimal: Path) -> None:
        """Not a test of this product - a demonstration that enabling is load-bearing."""
        from vtkmodules.vtkIOCGNSReader import vtkCGNSReader

        plain = vtkCGNSReader()
        plain.SetFileName(str(minimal))
        plain.Update()
        leaf = plain.GetOutput().GetBlock(0).GetBlock(0)

        assert leaf.GetPointData().GetNumberOfArrays() == 0

    def test_a_result_that_did_not_arrive_stops_the_read(self, minimal: Path) -> None:
        from engine.completeness import ResultsLost, check_nothing_was_dropped

        with pytest.raises(ResultsLost) as refusal:
            check_nothing_was_dropped({"stress"}, None, evidence="E-137")
        assert "stress" in str(refusal.value)


class TestTheUnitTheFileDeclaresAndTheReaderDoesNotGive:
    """ingest/AC-034. CGNS carries `DimensionalUnits`; `vtkCGNSReader` exposes no accessor whose name
    contains `unit`, `dimension` or `dataclass` - not one (E-137). The unit stays undeclared, and the
    user is told that the file said something rather than that it said nothing: only one of those two
    can be fixed by asking the solver."""

    def test_the_field_has_no_declared_unit(self, minimal: Path) -> None:
        dataset = reader.read_case(minimal).present[0].dataset

        assert dataset.fields["stress"].unit is None
        assert Caveat.UNDECLARED_UNIT in dataset.maximum("stress").caveats

    def test_the_reader_says_which_declaration_it_did_not_read(self, minimal: Path) -> None:
        level, gaps = reader.support_level(minimal)

        assert level == "Verified"
        assert "DimensionalUnits" in gaps

    def test_the_gaps_name_what_is_unexercised(self, minimal: Path) -> None:
        """AC-033: the specific gaps of this reader, not a generic warning. A fixture written here is
        narrower than a solver's file and the level has to say so."""
        _, gaps = reader.support_level(minimal)

        assert "multi-zone" in gaps
        assert "ADF" in gaps

    def test_the_format_could_not_be_registered_without_saying_so(self) -> None:
        """`ReaderChoice` refuses construction for a format that carries unit information when the
        reader does not say what it leaves unread (TASK-003). This is that rule firing on the format it
        was written for, two months before the format arrived."""
        from engine.reader import ReaderChoice
        from vtkmodules.vtkIOCGNSReader import vtkCGNSReader

        with pytest.raises(ValueError) as refusal:
            ReaderChoice(".cgns", vtkCGNSReader, "Verified")
        assert "LengthUnits and DimensionalExponents" in str(refusal.value)


class TestTheFixtureIsMinimalOnPurpose:
    def test_it_declares_the_units_even_though_nothing_reads_them(self, minimal: Path) -> None:
        """If the declaration were absent from the fixture, the test above would pass for the wrong
        reason - an undeclared unit from a file that declared nothing."""
        import h5py

        with h5py.File(minimal, "r") as handle:
            declared = handle["Base"]["DimensionalUnits"][" data"][()]
        assert b"Meter" in np.asarray(declared).tobytes()
