"""CGNS: the one format that declares its units, and the one this product cannot read them from.

The fixture is written here rather than collected. The toolkit ships three CGNS reader classes and **no
writer** (E-137), so XC-085's rule - fixtures are generated by this project's own test code wherever the
format allows it - has no writer to reach for. Its stated fallback was an outside file with recorded
terms; writing the CGNS/HDF5 node layout directly turns out to be the shorter route, and it keeps the
rule intact for six of six Verified formats rather than five.

What that fixture proves is bounded and the support level says so: one base, one unstructured zone, one
field, units declared. Multi-zone, structured zones, boundary conditions and ADF-format CGNS are
unexercised.

Verifies: ingest/AC-032, AC-033, AC-034, ingest/TASK-032.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from conftest import requires_h5py, requires_vtk

requires_vtk()
requires_h5py()

import numpy as np  # noqa: E402

from domain_core.reported_value import Caveat  # noqa: E402
from engine import reader  # noqa: E402
from cgns_fixture import write_minimal_cgns, write_transient_cgns  # noqa: E402


@pytest.fixture
def minimal(tmp_path: Path) -> Path:
    return write_minimal_cgns(tmp_path / "minimal.cgns")


class TestWhatTheFileHoldsArrives:
    def test_the_zone_reads_as_one_part_of_one_case(self, minimal: Path) -> None:
        case = reader.read_case(minimal)

        assert case.contents.parts == 1
        assert case.present[0].label.endswith("Base / Zone")

    def test_the_geometry_is_the_geometry_the_file_declares(self, minimal: Path) -> None:
        dataset = reader.read_case(minimal).present[0].dataset

        assert dataset.point_count == 4
        assert dataset.cell_count == 2
        assert set(dataset.cells.types.tolist()) == {5}  # VTK_TRIANGLE

    def test_the_result_arrives(self, minimal: Path) -> None:
        """The reader reads no arrays until each is switched on (E-137) - the same defect as Exodus
        through a different API, which is why the check that catches it is shared."""
        dataset = reader.read_case(minimal).present[0].dataset

        assert sorted(dataset.fields) == ["stress"]
        assert dataset.maximum("stress").value == 90.0

    def test_the_defaults_would_have_dropped_it(self, minimal: Path) -> None:
        """Not a test of this product - a demonstration that enabling is load-bearing."""
        from vtkmodules.vtkIOCGNSReader import vtkCGNSReader

        plain = vtkCGNSReader()
        plain.SetFileName(str(minimal))
        plain.Update()
        leaf = plain.GetOutput().GetBlock(0).GetBlock(0)

        assert leaf.GetPointData().GetNumberOfArrays() == 0

    def test_a_result_that_did_not_arrive_stops_the_read(self, minimal: Path) -> None:
        from engine.completeness import ResultsLost, check_nothing_was_dropped

        with pytest.raises(ResultsLost) as refusal:
            check_nothing_was_dropped({"stress"}, None, evidence="E-137")
        assert "stress" in str(refusal.value)


class TestTheUnitTheFileDeclaresAndTheReaderDoesNotGive:
    """ingest/AC-034. CGNS carries `DimensionalUnits`; `vtkCGNSReader` exposes no accessor whose name
    contains `unit`, `dimension` or `dataclass` - not one (E-137). The unit stays undeclared, and the
    user is told that the file said something rather than that it said nothing: only one of those two
    can be fixed by asking the solver."""

    def test_the_field_has_no_declared_unit(self, minimal: Path) -> None:
        dataset = reader.read_case(minimal).present[0].dataset

        assert dataset.fields["stress"].unit is None
        assert Caveat.UNDECLARED_UNIT in dataset.maximum("stress").caveats

    def test_the_reader_says_which_declaration_it_did_not_read(self, minimal: Path) -> None:
        level, gaps = reader.support_level(minimal)

        assert level == "Verified"
        assert "DimensionalUnits" in gaps

    def test_the_gaps_name_what_is_unexercised(self, minimal: Path) -> None:
        """AC-033: the specific gaps of this reader, not a generic warning. A fixture written here is
        narrower than a solver's file and the level has to say so."""
        _, gaps = reader.support_level(minimal)

        assert "multi-zone" in gaps
        assert "ADF" in gaps

    def test_the_format_could_not_be_registered_without_saying_so(self) -> None:
        """`ReaderChoice` refuses construction for a format that carries unit information when the
        reader does not say what it leaves unread (TASK-003). This is that rule firing on the format it
        was written for, two months before the format arrived."""
        from engine.reader import ReaderChoice
        from vtkmodules.vtkIOCGNSReader import vtkCGNSReader

        with pytest.raises(ValueError) as refusal:
            ReaderChoice(".cgns", vtkCGNSReader, "Verified")
        assert "LengthUnits and DimensionalExponents" in str(refusal.value)


class TestTheFixtureIsMinimalOnPurpose:
    def test_it_declares_the_units_even_though_nothing_reads_them(self, minimal: Path) -> None:
        """If the declaration were absent from the fixture, the test above would pass for the wrong
        reason - an undeclared unit from a file that declared nothing."""
        import h5py

        with h5py.File(minimal, "r") as handle:
            declared = handle["Base"]["DimensionalUnits"][" data"][()]
        assert b"Meter" in np.asarray(declared).tobytes()


class TestTheSequenceTheFileDeclares:
    """GL-036. CGNS states its values in `BaseIterativeData_t` and states nothing about what they are;
    both halves have to survive to the @Case (E-138)."""

    def test_the_values_arrive(self, tmp_path: Path) -> None:
        case = reader.read_case(write_transient_cgns(tmp_path / "t.cgns"))

        assert case.contents.axis.positions == (0.0, 0.5)
        assert case.contents.steps == 2

    def test_the_kind_stays_undeclared(self, tmp_path: Path) -> None:
        """The file does say - `SimulationType_t` - and the reader exposes no accessor for it, exactly
        as it exposes none for the units."""
        from domain_core.case_contents import AxisKind

        case = reader.read_case(write_transient_cgns(tmp_path / "t.cgns"))

        assert case.contents.axis.kind is AxisKind.UNDECLARED
        assert "何を刻む値か" in case.describe()

    def test_a_steady_file_reports_no_axis_rather_than_a_value_nobody_wrote(
        self, tmp_path: Path
    ) -> None:
        """The reader publishes `TIME_STEPS = [0.0]` for a file with no iterative data at all, while a
        plain `.vtu` publishes the key not at all. Reporting that 0.0 as a position would put a number
        in front of a reader that the file never wrote."""
        from domain_core.case_contents import AxisKind

        case = reader.read_case(write_minimal_cgns(tmp_path / "s.cgns"))

        assert case.contents.axis.kind is AxisKind.NONE
        assert case.contents.axis.positions is None
        assert "結果軸なし" in case.describe()

class TestAZoneTheReaderCannotReadIsAnAbsence:
    """AC-027, XC-272. A zone with a name and no coordinates comes back from the toolkit's reader with
    points allocated from the declared size, no cells, and an error on its own log that reaches nobody
    (E-210). The case says the part is missing rather than counting a part of nothing."""

    def test_the_zone_is_a_missing_part_and_the_case_is_partial(self, tmp_path: Path) -> None:
        import h5py
        from cgns_fixture import node, text

        path = write_minimal_cgns(tmp_path / "assembly.cgns")
        with h5py.File(path, "a") as handle:
            ghost = node(handle["Base"], "Ghost", "Zone_t", np.array([[4, 2, 0]], dtype=np.int32), "I4")
            node(ghost, "ZoneType", "ZoneType_t", text("Unstructured"), "C1")

        case = reader.read_case(path)

        assert case.is_partial is True
        assert [part.label for part in case.present] == ["assembly / Base / Zone"]
        assert case.contents.missing_parts == ("assembly / Base / Ghost（要素なし）",)
        assert [(part.path, part.reason) for part in case.absent] == [(("assembly", "Base", "Ghost"), "要素なし")]
        assert "不足 1 件" in case.describe() and "Ghost" in case.describe()

    def test_the_engine_lists_the_absence_and_says_partial(self, tmp_path: Path) -> None:
        """What the interface reads: `dataset.describe` says partial and `dataset.parts` names the
        part the reader could not fill, so a screen can say which rather than "some"."""
        import h5py
        from cgns_fixture import node, text
        from service.command.surface import Command, Status
        from test_handlers import opened

        path = write_minimal_cgns(tmp_path / "assembly.cgns")
        with h5py.File(path, "a") as handle:
            ghost = node(handle["Base"], "Ghost", "Zone_t", np.array([[4, 2, 0]], dtype=np.int32), "I4")
            node(ghost, "ZoneType", "ZoneType_t", text("Unstructured"), "C1")
        surface, _, _ = opened(tmp_path)

        loaded = surface.submit(Command("dataset.load", {"caseId": "case:1", "filePaths": [str(path)]}))

        assert loaded.status is Status.APPLIED, loaded.reason
        assert any("不完全" in one and "Ghost" in one for one in loaded.warnings)
        dataset_id = loaded.value["datasetId"]
        assert surface.submit(Command("dataset.describe", {"datasetId": dataset_id})).value["partial"] is True
        parts = surface.submit(Command("dataset.parts", {"datasetId": dataset_id})).value["parts"]
        absent = [one for one in parts if one["type"] == "absent"]
        # The name is the file's, the reason is the reader's, and the path is where the file put it -
        # three facts, carried as three (XC-274); until this change the name carried the reason.
        assert [(one["name"], one["reason"], one["path"], one["parentId"]) for one in absent] == [
            ("assembly / Base / Ghost", "要素なし", ["assembly", "Base", "Ghost"], "assembly / Base"),
        ]
        assert absent[0]["pointCount"] == 0 and absent[0]["cellCount"] == 0


class TestReadingAnotherStep:
    """XC-283, view/AC-033. The file declares two steps; asking for the second reads the second's
    values, and asking for a third reads nothing and names what there is. E-211 is the measurement
    behind the design, kept here so it is taken again on every run."""

    def test_the_second_step_s_values_arrive_when_asked_for(self, tmp_path: Path) -> None:
        path = write_transient_cgns(tmp_path / "t.cgns")

        first = reader.read_case(path)
        second = reader.read_case(path, step=1)

        assert np.asarray(first.present[0].dataset.fields["stress"].values).tolist() == [10.0, 20.0, 90.0, 40.0]
        assert np.asarray(second.present[0].dataset.fields["stress"].values).tolist() == [11.0, 21.0, 91.0, 41.0]
        assert second.contents.axis == first.contents.axis, "the axis is the whole sequence at every step"
        assert second.contents.steps == 2

    def test_a_step_the_file_does_not_have_is_refused_and_nothing_nearer_is_read(self, tmp_path: Path) -> None:
        from domain_core.case_contents import PositionError

        path = write_transient_cgns(tmp_path / "t.cgns")

        with pytest.raises(PositionError, match="ステップ番号 2"):
            reader.read_case(path, step=2)
        with pytest.raises(PositionError, match="定常"):
            reader.read_case(write_minimal_cgns(tmp_path / "s.cgns"), step=1)

    def test_the_toolkit_hands_over_the_next_declared_step_for_a_value_between_two(self, tmp_path: Path) -> None:
        """E-211, measured: `UpdateTimeStep(0.25)` on a file declaring 0.0 and 0.5 hands over the
        values at 0.5 and writes 0.5 on the output's `DATA_TIME_STEP`, while the plain first
        `Update()` writes nothing there. Which is why a step is asked for by its ordinal, only a
        declared value is ever requested, and the delivered one is checked (`reader.read_case`)."""
        from engine.result_axis import delivered_position

        path = write_transient_cgns(tmp_path / "t.cgns")
        choice = reader._READERS[".cgns"]
        toolkit = choice.factory()
        toolkit.SetFileName(str(path))
        assert choice.prepare is not None
        choice.prepare(toolkit)
        toolkit.Update()
        assert delivered_position(toolkit.GetOutputDataObject(0)) is None

        toolkit.UpdateTimeStep(0.25)

        assert delivered_position(toolkit.GetOutputDataObject(0)) == 0.5
        parts: list = []
        reader._walk(toolkit.GetOutputDataObject(0), ("t",), parts, [])
        assert np.asarray(parts[0].dataset.fields["stress"].values).tolist() == [11.0, 21.0, 91.0, 41.0]
