/* MOD-017: the design states' dispatcher. `Operation` and `OPERATIONS` come from generated.ts, the
 * one file written from CT-003 (XC-252) - this file used to carry its own copy of the union, marked
 * "generated" and regenerated by nothing, and it fell behind the contract the moment an operation
 * was added. `submit` logs and returns: a design state executes nothing and says so. */
import { OPERATIONS } from "./generated";
import type { Operation } from "./generated";

export { OPERATIONS };
export type { Operation };

export type Submission = { operation: Operation; parameters: Record<string, unknown> };

/* Mockup 2 is design states: nothing is wired to an engine here, and pretending otherwise would
 * make the mockup evidence of implemented behaviour, which it never is. The one submit path
 * exists so every screen already dispatches through it (INV-006); the typed client in engine.ts
 * is the transport, and validate/check_interface_commands.py holds these literals to CT-003. */
export function submit(submission: Submission): { status: "design-state" } {
  console.info("command (design state, not executed):", submission.operation, submission.parameters);
  return { status: "design-state" };
}
