"""Gate: the interface's types are generated from CT-003, and still match it.

XC-252 says the vocabulary crosses the language boundary by generation, not by a second definition -
and until 2026-09-19 nothing regenerated or compared anything. `src/ui/client/operations.ts` carried
a hand-maintained union of operation names whose own header said "Regenerate with: python tools not
needed", which is a file claiming to be generated by nothing.

What this writes, and why only this: **the shape of what crosses the wire**. One parameter type and
one result type per operation, the operation names, and the protocol version. Not behaviour - units,
precision and the invariants stay in Python and are reached by asking the service (XC-252).

    python validate/check_client_types.py            # compare, fail on drift
    python validate/check_client_types.py --write    # regenerate

Exit codes: 0 the generated file matches the contract, 1 it does not, **3 the comparison could not be
made here** - no interface tree to compare against. Three is not success.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from check_commands import catalogue_rows

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "specs" / "contracts" / "schema" / "CT-003.json"
CONTRACT = ROOT / "specs" / "contracts" / "CT-003_engine_api.md"
DOCUMENT_SCHEMA = ROOT / "specs" / "contracts" / "schema" / "CT-001.json"
GENERATED = ROOT / "src" / "ui" / "client" / "generated.ts"
NEWLINE = "\n"

#: JSON Schema types as TypeScript. `integer` and `number` are both `number`: TypeScript has one, and
#: pretending otherwise would be a type the language cannot enforce.
PRIMITIVES = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}

#: A shape defined once in another contract and referenced from CT-003 (XC-266): named here, and
#: generated below from the definition it points at. Anything else referenced becomes `unknown`,
#: which fails the build at the first use rather than passing as `any`.
REFERENCED = {
    "CT-001.json#/$defs/recordedTime": "RecordedTime",
    "CT-004.json#/properties/camera": "CameraDefinition",
}

#: What each referenced type means, written above it in the generated file.
REFERENCED_DOC = {
    "RecordedTime": (
        "/** A time this product recorded: the UTC instant, and the offset of the zone it was recorded",
        "  * in - or null where a record written before the offset was kept has none (XC-142, XC-266).",
        "  * Defined once, in CT-001's $defs.recordedTime, and referenced by every contract. */",
    ),
    "CameraDefinition": (
        "/** Where a picture is looked at from: CT-004's camera, referenced by view.render and view.pick",
        "  * so a camera move can be drawn without becoming a change to the view's definition (XC-270). */",
    ),
}


def schema() -> dict:
    return json.loads(SCHEMA.read_text(encoding="utf-8"))


def document_schema() -> dict:
    return json.loads(DOCUMENT_SCHEMA.read_text(encoding="utf-8"))


def resolve(reference: str) -> dict:
    """The node a `<file>#<pointer>` reference names, read from the contract that defines it."""
    file_name, _, pointer = reference.partition("#")
    node: object = json.loads((SCHEMA.parent / file_name).read_text(encoding="utf-8"))
    for part in pointer.strip("/").split("/"):
        node = node[part]  # type: ignore[index]
    return node  # type: ignore[return-value]


def protocol_version() -> str:
    for line in CONTRACT.read_text(encoding="utf-8").splitlines():
        if line.startswith("- version:"):
            return line.split(":", 1)[1].strip()
    return ""


def type_of(node: object, indent: int = 0) -> str:
    """One JSON Schema node as a TypeScript type.

    Unknown shapes become `unknown` rather than `any`: `any` disables the checking this file exists
    to provide, and a caller that must narrow an `unknown` is a caller that has read the contract.
    """
    if not isinstance(node, dict):
        return "unknown"
    reference = node.get("$ref")
    if reference:
        if reference in REFERENCED:
            return REFERENCED[reference]
        # A reference into CT-003's own $defs: the reported value has its named type below, and any
        # other local definition is written out where it is used, so nothing becomes `unknown` for
        # being defined once and referenced twice.
        if reference == "#/$defs/reportedValue":
            return "ReportedValue"
        if reference.startswith("#/$defs/"):
            return type_of(schema()["$defs"][reference.rsplit("/", 1)[1]], indent)
        return "unknown"
    if "enum" in node:
        return " | ".join(json.dumps(one, ensure_ascii=False) for one in node["enum"])
    kind = node.get("type")
    if isinstance(kind, list):
        return " | ".join(PRIMITIVES.get(one, "null" if one == "null" else "unknown") for one in kind)
    if kind == "array":
        return f"readonly ({type_of(node.get('items'), indent)})[]"
    if kind == "object":
        properties = node.get("properties") or {}
        if not properties:
            return "Record<string, unknown>"
        required = set(node.get("required") or [])
        pad = "  " * (indent + 1)
        lines = [
            f"{pad}{name if name.isidentifier() else json.dumps(name)}"
            f"{'' if name in required else '?'}: {type_of(child, indent + 1)};"
            for name, child in properties.items()
        ]
        return "{\n" + NEWLINE.join(lines) + NEWLINE + "  " * indent + "}"
    if kind in PRIMITIVES:
        return PRIMITIVES[kind]
    return "unknown"


def name_of(operation: str) -> str:
    """`dataset.probe` as `DatasetProbe` - one TypeScript identifier per operation."""
    return "".join(part[:1].upper() + part[1:] for part in operation.replace(".", " ").split())


def facts_line(operation: str, parameters: dict, results: dict, classes: dict[str, bool]) -> str:
    """One operation's facts as a TypeScript entry. The class comes from the catalogue table, the
    same column the engine's catalogue is generated from; an operation the table does not
    class is a contract error, not a default."""
    if operation not in classes:
        raise SystemExit(f"check_client_types: {operation} is in the schema and not in the CT-003 table")
    required = list(parameters.get("required", []))
    optional = [name for name in parameters.get("properties", {}) if name not in required]
    answers = list(results.get("properties", {}))
    return (
        f'  {json.dumps(operation)}: {{ writes: {str(classes[operation]).lower()}, '
        f'required: {json.dumps(required)}, optional: {json.dumps(optional)}, answers: {json.dumps(answers)} }},'
    )


def render() -> str:
    document = schema()
    parameters = document["$defs"]["operationParameters"]["properties"]
    results = document["$defs"]["operationResults"]["properties"]
    operations = list(parameters)
    classes = dict(catalogue_rows())

    lines = [
        "/* GENERATED from specs/contracts/schema/CT-003.json by validate/check_client_types.py.",
        " * Do not edit by hand: the gate regenerates this file and compares, so an edit here fails",
        " * the build rather than changing anything (XC-252).",
        " *",
        " * What is generated is the shape of what crosses the wire - the operations, what each takes",
        " * and what each answers. What is NOT generated is behaviour: units, precision and the",
        " * invariants stay in Python and are reached by asking the service, never reimplemented here.",
        " */",
        "",
        f'export const PROTOCOL_VERSION = "{protocol_version()}";',
        "",
        "/* The wire's own names, from CT-003's $defs.transport (XC-258). The engine generates the",
        " * same values from the same place; neither side is derived from the other (XC-252). */",
        *[
            f'export const {name}: string = {json.dumps(node.get("const", ""), ensure_ascii=False)};'
            for name, node in ((document.get("$defs", {}).get("transport", {}).get("properties")) or {}).items()
            for name in [({"tokenHeader": "TOKEN_HEADER", "commandPath": "COMMAND_PATH",
                           "handlePath": "HANDLE_PATH", "healthPath": "HEALTH_PATH",
                           "connectionFile": "CONNECTION_FILE"}).get(name, name.upper())]
        ],
        "",
        "export type Operation =",
        *[f'  | "{one}"' for one in operations],
        "  ;",
        "",
        "export const OPERATIONS: readonly Operation[] = [",
        *[f'  "{one}",' for one in operations],
        "];",
        "",
        "/** What each operation is, for a list a person reads (XC-277): whether it writes - from the",
        " *  catalogue table's class column - and its parameters and answer fields by name, from the",
        " *  schema. Behaviour is not here: what an operation does is the engine's to say. */",
        "export interface OperationFacts {",
        "  readonly writes: boolean;",
        "  readonly required: readonly string[];",
        "  readonly optional: readonly string[];",
        "  readonly answers: readonly string[];",
        "}",
        "",
        "export const OPERATION_FACTS: Readonly<Record<Operation, OperationFacts>> = {",
        *[facts_line(one, parameters[one], results.get(one, {}), classes) for one in operations],
        "};",
        "",
        "/** What each operation takes. From CT-003's $defs.operationParameters. */",
        "export interface Parameters {",
    ]
    for operation in operations:
        lines.append(f'  {json.dumps(operation)}: {type_of(parameters[operation], 1)};')
    lines += [
        "}",
        "",
        "/** What each operation answers. From CT-003's $defs.operationResults. */",
        "export interface Results {",
    ]
    for operation in operations:
        lines.append(f'  {json.dumps(operation)}: {type_of(results.get(operation, {}), 1)};')
    lines += [
        "}",
        "",
        "/** A number this product reports: its unit, the digits it honestly carries, and where it",
        "  * came from. Never a bare number - one without its unit is a number in whatever unit the",
        "  * reader assumed (XC-003, XC-253). */",
        "export type ReportedValue = " + type_of(document["$defs"]["reportedValue"], 0) + ";",
        "",
    ]
    for reference, name in REFERENCED.items():
        lines += [*REFERENCED_DOC[name], f"export type {name} = " + type_of(resolve(reference), 0) + ";", ""]
    return NEWLINE.join(lines)


def main(argv: list[str]) -> int:
    if not GENERATED.parent.exists():
        print("check_client_types: there is no src/ui/client here, so nothing was compared.")
        print("  Refusing to report success for a comparison that did not happen.")
        return 3

    produced = render()
    if "--write" in argv:
        GENERATED.write_text(produced, encoding="utf-8", newline=NEWLINE)
        print(f"wrote {GENERATED.relative_to(ROOT).as_posix()} from CT-003")
        return 0

    if not GENERATED.exists():
        print(f"[client-types] {GENERATED.relative_to(ROOT).as_posix()} does not exist.")
        print("  Generate it: python validate/check_client_types.py --write")
        return 1

    current = GENERATED.read_text(encoding="utf-8")
    if current != produced:
        print(f"[client-types] {GENERATED.relative_to(ROOT).as_posix()} does not match CT-003.")
        print("  Either the contract changed and this was not regenerated, or this was edited by hand.")
        print("  Regenerate: python validate/check_client_types.py --write")
        return 1

    print()
    print("NOT checked: whether the interface uses these types. This gate compares a generated file")
    print("  against the contract and parses no TypeScript, so a screen calling an operation with the")
    print("  wrong parameters is caught by tsc, not here")
    print()
    print("The interface's generated types match CT-003.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
