/* GENERATED from mockups/ui/lib/screen-catalog.json (mockup 1's own list - one source of truth)
 * plus the three areas 16_application_model names as specified-but-surfaceless: information,
 * find, diff. Do not edit the mockup-1 entries here; edit the JSON and regenerate. */
import type { ScreenId } from "../state/session";

export type Scenario = { id: string; screen: ScreenId; variant: string; label: string; intent: string };

export const SCENARIOS: readonly Scenario[] = [
  { id: "home.default", screen: "home" as ScreenId, variant: "default", label: "ワークスペース一覧", intent: "検索と絞り込みを使い、ワークスペースを開く・作る・再訪する。" },
  { id: "home.first-run", screen: "home" as ScreenId, variant: "first-run", label: "初回起動", intent: "同梱サンプルを先に提示し、次にドロップ領域付きの空ワークスペースを提示する。" },
  { id: "home.import-review", screen: "home" as ScreenId, variant: "import-review", label: "取込前確認", intent: "対応レベル、フィールド関連、未宣言単位、座標フレームを確認してから読み込む。" },
  { id: "home.importing", screen: "home" as ScreenId, variant: "importing", label: "取込中", intent: "元ファイルを変更せず、いつでもキャンセルできる読み込みを表示する。" },
  { id: "home.unreadable-file", screen: "home" as ScreenId, variant: "unreadable-file", label: "読込不能ファイル", intent: "不確かな部分ケースを作らず、拒否したファイルと理由を明示する。" },
  { id: "simulation.default", screen: "simulation" as ScreenId, variant: "default", label: "保存フロー", intent: "1回以上の外部ソルバー実行の条件をまとめた保存フローを、解決状態つきで確認する。" },
  { id: "simulation.empty", screen: "simulation" as ScreenId, variant: "empty", label: "未作成", intent: "保存されたシミュレーションが無い状態と、新規作成の入口を提示する。" },
  { id: "simulation.unavailable", screen: "simulation" as ScreenId, variant: "unavailable", label: "シミュレーション・後続リリース", intent: "r1ではソルバー実行が未提供であることと、代替となるパイプライン取込を案内する。" },
  { id: "simulation.unresolved", screen: "simulation" as ScreenId, variant: "unresolved", label: "条件未解決", intent: "未宣言変数と未接続アダプターを名指しし、実行を拒否したまま定義を保持する。" },
  { id: "pipeline.default", screen: "pipeline" as ScreenId, variant: "default", label: "自動化・パイプライン編集", intent: "専用の自動化モードで明示的なユニットを編集し、各ユニットに累積対象ケース数を表示する。" },
  { id: "pipeline.dry-run", screen: "pipeline" as ScreenId, variant: "dry-run", label: "自動化・ドライラン結果", intent: "実行前にケース、入れ子、生成物、スキップ対象をプレビューする。" },
  { id: "pipeline.empty", screen: "pipeline" as ScreenId, variant: "empty", label: "自動化・空のパイプライン", intent: "右側のユニット追加から開始し、実行前のドライランへ案内する。" },
  { id: "pipeline.failed", screen: "pipeline" as ScreenId, variant: "failed", label: "自動化・ケース失敗", intent: "失敗をユニットとケース上に表示し、そのケースの依存ユニットだけをスキップする。" },
  { id: "pipeline.unit-reference", screen: "pipeline" as ScreenId, variant: "unit-reference", label: "ユニットの参照先", intent: "11_ui.md「Comparing」・XC-211。ビュー・グラフ・レポートを作るユニットは、どの項目を作るかを名指しする。比較も選べる。未選択なら未解決として実行を拒む。" },
  { id: "pipeline.running", screen: "pipeline" as ScreenId, variant: "running", label: "自動化・実行中", intent: "閲覧を許可したままワークスペース編集を止め、ユニット境界でキャンセルする。" },
  { id: "pipeline.scope-confirmation", screen: "pipeline" as ScreenId, variant: "scope-confirmation", label: "自動化・破壊操作の範囲確認", intent: "破壊的ユニットを許可する前に、影響する対象セットを明示する。" },
  { id: "view.assistant-drawer", screen: "view" as ScreenId, variant: "assistant-drawer", label: "ビュー・会話ドロワー", intent: "中央表示に重なる右側ドロワーで同じ会話を続け、右プロパティ欄と素材ライブラリを維持する。" },
  { id: "view.axis-error", screen: "view" as ScreenId, variant: "axis-error", label: "結果軸位置なし", intent: "近傍結果へ丸めず、存在しない位置を明示する。" },
  { id: "view.background", screen: "view" as ScreenId, variant: "background", label: "ビュー・背景", intent: "11_ui.md・XC-215。背景の種類を、単色・グラデーション・画像・環境の見本から選ぶ。" },
  { id: "view.camera-unresolved", screen: "view" as ScreenId, variant: "camera-unresolved", label: "カメラ・視点未解決", intent: "規則が参照する数量がこのケースに無い場合、名指しして拒否し、カメラを動かさない。" },
  { id: "view.cameras", screen: "view" as ScreenId, variant: "cameras", label: "カメラ・複数登録", intent: "1つのビューに複数のカメラを保存し、どの画面がどれを覗くかと、規則の解決結果を示す。" },
  { id: "view.comparison", screen: "view" as ScreenId, variant: "comparison", label: "比較ビュー・グリッド", intent: "基準ビューを1本の軸で振り、メンバーを格子に並べる。全ペインでカラーマップと範囲を共有する。" },
  { id: "view.comparison-borrowed", screen: "view" as ScreenId, variant: "comparison-borrowed", label: "比較ビュー・借りている設定", intent: "比較が持たない設定は、編集できる複製ではなく基準ビューのものとして名指しし、そこへ移動できるようにする。" },
  { id: "view.comparison-columns", screen: "view" as ScreenId, variant: "comparison-columns", label: "比較・列数を指定", intent: "11_ui.md「Comparing」・XC-205。6メンバーを3列2行に折り返します。行数はメンバー数から決まるため、どの列数でも絵に出ないメンバーは生まれません。" },
  { id: "view.comparison-output", screen: "view" as ScreenId, variant: "comparison-output", label: "比較・成果物タブ", intent: "11_ui.md「Comparing」・XC-212。比較の出力はカメラと結果位置を訊き直さず、軸か共有かを表示する。結果位置を軸にした比較は動画にできない理由を示す。" },
  { id: "view.comparison-overlay", screen: "view" as ScreenId, variant: "comparison-overlay", label: "比較ビュー・重ね合わせ", intent: "同じ比較を1枚に重ねる。結果色を持てるのは1メンバーのみで、残りは参照形状として描く。" },
  { id: "view.comparison-range", screen: "view" as ScreenId, variant: "comparison-range", label: "比較ビュー・時間を等分", intent: "結果軸を等分してメンバーを生成し、保存位置への丸めと重複を明示する。ブックマークを先に作らずに時間比較を作る。" },
  { id: "view.default", screen: "view" as ScreenId, variant: "default", label: "ビュー・1画面", intent: "選択ケースを開いているビューで1画面に描画する。" },
  { id: "view.deformation", screen: "view" as ScreenId, variant: "deformation", label: "変形表示", intent: "変形倍率を画面に描き込み、報告値は未変形形状から計算されることを明示する。" },
  { id: "view.develop-grade", screen: "view" as ScreenId, variant: "develop-grade", label: "描画・現像", intent: "露光やトーンマップのプリセットを選び、既定の計測では無補正であることと凡例の整合を示す。" },
  { id: "view.empty", screen: "view" as ScreenId, variant: "empty", label: "ビュー・空状態", intent: "開始プリセットとワークスペースのビュー一覧を提示する。" },
  { id: "view.library-collapsed", screen: "view" as ScreenId, variant: "library-collapsed", label: "素材ライブラリ・閉じた状態", intent: "中央表示の縦幅を優先し、入力欄の直上に細いライブラリ見出しだけを残す。" },
  { id: "view.library-expanded", screen: "view" as ScreenId, variant: "library-expanded", label: "素材ライブラリ・拡張表示", intent: "ライブラリを縦に拡張して複数行を閲覧しながら、右側の編集領域の高さを維持する。" },
  { id: "view.library-narrow", screen: "view" as ScreenId, variant: "library-narrow", label: "素材ライブラリ・狭幅表示", intent: "狭い表示では中央画面を押し縮めず、入力欄の上に重なる下部ドロワーとして開く。" },
  { id: "view.library-one-row", screen: "view" as ScreenId, variant: "library-one-row", label: "素材ライブラリ・1行表示", intent: "サムネイルを途中で切らず、適用可能な素材を完全な1行で表示する。" },
  { id: "view.library-searching", screen: "view" as ScreenId, variant: "library-searching", label: "素材ライブラリ・検索中", intent: "サンプルとオリジナル、文字列、タグ、並び順を分離して素材を絞り込む。" },
  { id: "view.library-selected", screen: "view" as ScreenId, variant: "library-selected", label: "素材ライブラリ・選択中", intent: "クリックは選択と確認に使い、ドラッグまたは明示的な適用操作で現在の対象へ反映する。" },
  { id: "view.material-composition", screen: "view" as ScreenId, variant: "material-composition", label: "マテリアル・解析入力未解決", intent: "複数Material Slot、MaterialXの必須解析入力、入力未解決時の診断マゼンタを同じマテリアル設定として表示する。" },
  { id: "view.object-analysis-mesh", screen: "view" as ScreenId, variant: "object-analysis-mesh", label: "オブジェクト・解析メッシュ", intent: "解析メッシュの参照元、表現、可視性を編集し、元データや解析値を変更しない。" },
  { id: "view.object-annotation", screen: "view" as ScreenId, variant: "object-annotation", label: "オブジェクト・テキスト注釈", intent: "オブジェクトで種類、アンカー、来歴を、条件付きテキストタブで内容と文字表現を編集する。" },
  { id: "view.object-effect", screen: "view" as ScreenId, variant: "object-effect", label: "オブジェクト・エフェクト", intent: "強調や装飾を表示専用として明記し、解析値を生成する機能に見せない。" },
  { id: "view.object-point-cloud", screen: "view" as ScreenId, variant: "object-point-cloud", label: "オブジェクト・点群", intent: "点の参照元、サイズ、色の結び付け、可視性だけを点群向けに表示する。" },
  { id: "view.object-reference-mesh", screen: "view" as ScreenId, variant: "object-reference-mesh", label: "オブジェクト・参照メッシュ", intent: "参照形状を解析メッシュと区別し、表示役割と外観だけを編集する。" },
  { id: "view.object-scalar-field", screen: "view" as ScreenId, variant: "object-scalar-field", label: "オブジェクト・スカラー場", intent: "フィールド、位置、成分、単位、カラーマップ、範囲、凡例を一つの結果表現として確認する。" },
  { id: "view.object-trajectory", screen: "view" as ScreenId, variant: "object-trajectory", label: "オブジェクト・流線と軌跡", intent: "未解決のフィールドやシードを既定値で補わず、積分と表示の定義を分離して示す。" },
  { id: "view.object-vector-field", screen: "view" as ScreenId, variant: "object-vector-field", label: "オブジェクト・ベクトル場", intent: "ベクトルの参照元、成分座標系、グリフ、密度、スケールを明示する。" },
  { id: "view.outliner-empty", screen: "view" as ScreenId, variant: "outliner-empty", label: "アウトライナー・空状態", intent: "データセット未読込ではサンプル構造を作らず、読込後に構成要素を表示すると案内する。" },
  { id: "view.outliner-flat", screen: "view" as ScreenId, variant: "outliner-flat", label: "アウトライナー・平坦構造", intent: "元ファイルに親子関係がなければ、推測せずデータセット直下の兄弟要素として表示する。" },
  { id: "view.output-motion", screen: "view" as ScreenId, variant: "output-motion", label: "出力・再生プリセット", intent: "再生範囲と速度の異なるプリセットを複数保存し、動画はプリセット1つとカメラ1台を名指しする。" },
  { id: "view.output-preflight", screen: "view" as ScreenId, variant: "output-preflight", label: "ビュー出力前確認", intent: "レンダラー、保存先、動画のカメラパスと時間対応を検査してから出力する。" },
  { id: "view.probe", screen: "view" as ScreenId, variant: "probe", label: "プローブ", intent: "点の値を単位・有効数字・由来つきで表示し、明示操作で変数として保持する。" },
  { id: "view.reduced", screen: "view" as ScreenId, variant: "reduced", label: "縮退表示", intent: "表示形状が縮退済みであると明示し、報告値は完全データから得る。" },
  { id: "view.renderer-error", screen: "view" as ScreenId, variant: "renderer-error", label: "レンダラー利用不能", intent: "失敗したバックエンドと、引き続き利用できる描画経路を明示する。" },
  { id: "view.result-bookmarks", screen: "view" as ScreenId, variant: "result-bookmarks", label: "結果軸ブックマーク", intent: "固定時刻・極値時刻・しきい値交差を登録し、ケースごとに解決した位置と値を表示する。" },
  { id: "view.split-four", screen: "view" as ScreenId, variant: "split-four", label: "ビュー・4分割", intent: "各画面のケース識別を保ちながら上限の4画面を比較する。" },
  { id: "view.split-output", screen: "view" as ScreenId, variant: "split-output", label: "分割中の出力タブ", intent: "11_ui.md「Comparing」・XC-210。分割は書き出しに含まれないことを、成果物タブで明示する。並べた図は比較項目から作る。" },
  { id: "view.split-three", screen: "view" as ScreenId, variant: "split-three", label: "ビュー・3分割", intent: "非対称の3分割でも各画面のケース識別を見失わない。" },
  { id: "view.split-two", screen: "view" as ScreenId, variant: "split-two", label: "ビュー・2分割", intent: "任意のカメラ同期を使って2画面を比較する。" },
  { id: "view.steady-result", screen: "view" as ScreenId, variant: "steady-result", label: "定常結果・再生なし", intent: "結果軸を持たないケースでは、再生オーバーレイを出さず、動画と再生プリセットを利用不可として名指しする。" },
  { id: "view.temporal-axis", screen: "view" as ScreenId, variant: "temporal-axis", label: "結果軸", intent: "名前付きの時間・モード・周波数軸を再生、移動、スクラブする。" },
  { id: "view.unresolved-template", screen: "view" as ScreenId, variant: "unresolved-template", label: "未解決テンプレート", intent: "描画前に解決できた項目と未解決項目を一覧表示する。" },
  { id: "graph.axes", screen: "graph" as ScreenId, variant: "axes", label: "グラフ・軸", intent: "11_ui.md・XC-213。軸を1本選び、表題・範囲・目盛・グリッドを設定する。範囲を固定するとデータを切り落とす旨を明示する。" },
  { id: "graph.axis-unit-conflict", screen: "graph" as ScreenId, variant: "axis-unit-conflict", label: "軸・単位が混在", intent: "11_ui.md・XC-228／XC-003。1本の軸に置かれた系列が異なる単位を宣言した場合、どちらかを軸に書かず「単位混在」と示し、単位は凡例に出す。" },
  { id: "graph.style", screen: "graph" as ScreenId, variant: "style", label: "グラフ・スタイル", intent: "11_ui.md・XC-215。配色・背景・マーカーを、名前ではなく描いた見本から選ぶ。名前は見本の下に残す。" },
  { id: "graph.default", screen: "graph" as ScreenId, variant: "default", label: "グラフ作成", intent: "単位、来歴、明示的ケース選択を伴う物理量から図を作る。" },
  { id: "graph.empty", screen: "graph" as ScreenId, variant: "empty", label: "グラフ開始方法", intent: "手動、推奨、アシスタント提案を、勝手に適用せず提示する。" },
  { id: "graph.no-points", screen: "graph" as ScreenId, variant: "no-points", label: "選択点なし", intent: "空グラフを描かず、選択を空にした条件を明示する。" },
  { id: "graph.output-preflight", screen: "graph" as ScreenId, variant: "output-preflight", label: "グラフ出力前確認", intent: "系列と単位の未解決を出力前に拒否し、既存成果物を変更しない。" },
  { id: "graph.series", screen: "graph" as ScreenId, variant: "series", label: "グラフ・系列", intent: "11_ui.md・XC-221。系列ごとに、描く数量と見え方を1行で設定する。見え方の既定はテーマにあり、系列はテーマの見本を第一選択として持つ。" },
  { id: "graph.series-unresolved", screen: "graph" as ScreenId, variant: "series-unresolved", label: "系列の参照未解決", intent: "系列ごとに数量、単位、来歴、式、欠損方針を編集し、未選択を明示する。" },
  { id: "report.blank", screen: "report" as ScreenId, variant: "blank", label: "空のレポート", intent: "同梱テンプレートと、意図的な空文書を提示する。" },
  { id: "report.commentary-review", screen: "report" as ScreenId, variant: "commentary-review", label: "生成コメントの利用確認", intent: "方向、深さ、モデル、検索許可、送信内容と費用を確定するまで生成を開始しない。" },
  { id: "report.drafting", screen: "report" as ScreenId, variant: "drafting", label: "レポート・執筆", intent: "11_ui.md・XC-214。方式と方針を決め、下書きを作り、確認するまで本文に入らない状態を示す。" },
  { id: "report.theme", screen: "report" as ScreenId, variant: "theme", label: "レポート・テーマ", intent: "11_ui.md・XC-214/XC-215。ページ・配色・書体を1つのテーマにまとめ、向き・余白・段組み・図表は描いた見本から選ぶ。書体は書体自身で表示する。" },
  { id: "report.default", screen: "report" as ScreenId, variant: "default", label: "レポート編集", intent: "明示したケース、ビュー、グラフ、参考資料から成果物を構成する。" },
  { id: "report.export-error", screen: "report" as ScreenId, variant: "export-error", label: "出力利用不能", intent: "前回成果物を上書きせず、出力形式と失敗理由を明示する。" },
  { id: "report.exporting", screen: "report" as ScreenId, variant: "exporting", label: "出力中", intent: "出力をキャンセル可能にし、同じ対象への二重出力を止める。" },
  { id: "report.output-preflight", screen: "report" as ScreenId, variant: "output-preflight", label: "レポート出力前確認", intent: "必須情報、字体、置換、未解決内容、保存先を一度に確認してから出力する。" },
  { id: "chat.assistant-error", screen: "chat" as ScreenId, variant: "assistant-error", label: "アシスタント失敗", intent: "未実行の内容を明示し、ワークスペースを変更しない。" },
  { id: "chat.default", screen: "chat" as ScreenId, variant: "default", label: "チャット", intent: "左右の吹き出しを使わず、同じ読み幅の縦方向の会話として質問と回答を続ける。" },
  { id: "chat.empty", screen: "chat" as ScreenId, variant: "empty", label: "新しい会話", intent: "作業済みと誤解させず、回答可能な質問例を示す。" },
  { id: "chat.outbound-request", screen: "chat" as ScreenId, variant: "outbound-request", label: "外部送信確認", intent: "端末外へ出す前に、正確な検索語と送信しないデータを表示する。" },
  { id: "settings.default", screen: "settings" as ScreenId, variant: "default", label: "設定", intent: "宣言単位、表示単位、座標系、レンダラー、アシスタント、ライブラリを設定する。" },
  { id: "settings.invalid", screen: "settings" as ScreenId, variant: "invalid", label: "無効な設定", intent: "無効値を入力時に拒否し、直前の値を維持する。" },
  { id: "settings.shortcuts", screen: "settings" as ScreenId, variant: "shortcuts", label: "ショートカット", intent: "コマンドとキーの一覧を示し、破壊的な操作が単一キーを持たないことを明示する。" },
  { id: "settings.support-bundle", screen: "settings" as ScreenId, variant: "support-bundle", label: "サポートバンドル確認", intent: "含める情報、要確認情報、除外する顧客データを作成前に列挙する。" },
  { id: "network.default", screen: "network" as ScreenId, variant: "default", label: "ネットワークと監査", intent: "端末外へ出せる内容を表示し、ローカル監査履歴を保持する。" },
  { id: "network.offline", screen: "network" as ScreenId, variant: "offline", label: "既定でオフライン", intent: "検索が未許可であることと、許可方法を説明する。" },
  { id: "network.refused", screen: "network" as ScreenId, variant: "refused", label: "要求拒否", intent: "送信せず、拒否したホストと要求を明示する。" },
  { id: "network.request-review", screen: "network" as ScreenId, variant: "request-review", label: "外部通信権限の確認", intent: "要求ごとの内容確認、機密情報の追加許可、ローカル監査を示してから許可する。" },
  { id: "information.default", screen: "information" as ScreenId, variant: "default", label: "データの中身", intent: "読み込んだファイルが実際に何を含むかを、いつでも読める場所（仕様が名指しした欠落画面）。" },
  { id: "information.empty", screen: "information" as ScreenId, variant: "empty", label: "未読込", intent: "何も読み込まれていない状態。構造を発明しない。" },
  { id: "information.limited", screen: "information" as ScreenId, variant: "limited", label: "限定対応の読み込み", intent: "offered 段のリーダーで読んだ場合、読めなかったものが名指しされる（XC-049）。" },
  { id: "find.default", screen: "find" as ScreenId, variant: "default", label: "条件選択", intent: "条件式・ID・しきい値で点やセルを選択し、何に解決したかを見る（仕様が名指しした欠落画面）。" },
  { id: "find.empty", screen: "find" as ScreenId, variant: "empty", label: "条件なし", intent: "空の条件は前の選択に触れない。" },
  { id: "find.unresolvable", screen: "find" as ScreenId, variant: "unresolvable", label: "解決できない名前", intent: "解決できない名前が文字位置つきで示され、何も選択されない。" },
  { id: "diff.default", screen: "diff" as ScreenId, variant: "default", label: "ケース差分", intent: "二ケースの差。方向・範囲外点数・往復誤差の三点開示が常に結果と共にある（XC-038）。" },
  { id: "diff.method", screen: "diff" as ScreenId, variant: "method", label: "方法の選択", intent: "共有メッシュか再標本化か。再標本化先は利用者が選ぶ。単位が違えば両方を名指しして拒否（INV-002）。" },
  { id: "diff.unresolved", screen: "diff" as ScreenId, variant: "unresolved", label: "片側にない量", intent: "片側にしかない量は名指しされ、差分は計算されない。" },
] as const;
